## Append samples of your project ##
resources:
  - networking_v1alpha1_dedicatedclbservice.yaml
  - networking_v1alpha1_dedicatedclblistener.yaml
  - networking_v1alpha1_dedicatedmulticlbservice.yaml
    # +kubebuilder:scaffold:manifestskustomizesamples
